framework:
    rate_limiter:
        forgot_password:
            policy: 'sliding_window'
            limit: 3
            interval: '15 minutes'
        reset_password:
            policy: 'sliding_window'
            limit: 5
            interval: '15 minutes'
        register:
            policy: 'sliding_window'
            limit: 5
            interval: '15 minutes'
        accept_invitation:
            policy: 'sliding_window'
            limit: 5
            interval: '15 minutes'
        resend_invitation:
            policy: 'sliding_window'
            limit: 3
            interval: '15 minutes'
        resend_verification:
            policy: 'sliding_window'
            limit: 3
            interval: '15 minutes'
